[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8" }
simula_core = { path = "../../crates/simula_core" }
simula_camera = { path = "../../crates/simula_camera" }
simula_viz = { path = "../../crates/simula_viz" }
simula_cad = { path = "../../crates/simula_cad" }
rand = "0.8.5"
bevy-inspector-egui = "0.12.0"

fj = { git = "https://github.com/hannobraun/Fornjot.git", rev = "ad7e8082949cb4907d7429b29af2df43b34b0c09" }
fj-math = { git = "https://github.com/hannobraun/Fornjot.git", rev = "ad7e8082949cb4907d7429b29af2df43b34b0c09" }
fj-operations = { git = "https://github.com/hannobraun/Fornjot.git", rev = "ad7e8082949cb4907d7429b29af2df43b34b0c09" }
fj-interop = { git = "https://github.com/hannobraun/Fornjot.git", rev = "ad7e8082949cb4907d7429b29af2df43b34b0c09" }
